import './globals.css'
import { Inter } from 'next/font/google'
import AppBar from './components/AppBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Corregir error de consola, tengo que trear el componente appBar aca/ cambiarlo por el body y que el children
// este dentro

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar/>
        {children}
        </body>
    </html>
  )
}
